export default [
  {
    path: '',
    name: 'demo-intro',
    displayName: 'Introduction',
    component: () => import('./views/pages/Introduction/index.vue'),
  },
  {
    path: 'accordion',
    name: 'demo-accordion',
    displayName: 'Accordion',
    component: () => import('./views/pages/DemoAccordion/index.vue'),
  },
  {
    path: 'alert',
    name: 'demo-alert',
    displayName: 'Alert',
    component: () => import('./views/pages/DemoAlerts/index.vue'),
  },
  {
    path: 'badges',
    name: 'demo-badges',
    displayName: 'Badges',
    component: () => import('./views/pages/DemoBadges/index.vue'),
  },
  {
    path: 'blockquote',
    name: 'demo-blockquote',
    displayName: 'Blockquote',
    component: () => import('./views/pages/DemoBlockquote/index.vue'),
  },
  {
    path: 'button',
    name: 'demo-button',
    displayName: 'Button',
    component: () => import('./views/pages/DemoButtons/index.vue'),
  },
  {
    path: 'button-group',
    name: 'demo-button-group',
    displayName: 'Button Group',
    component: () => import('./views/pages/DemoButtonGroup/index.vue'),
  },
  {
    path: 'cards',
    name: 'demo-cards',
    displayName: 'Cards',
    component: () => import('./views/pages/DemoCards/index.vue'),
  },
  {
    path: 'checkbox',
    name: 'demo-checkbox',
    displayName: 'Checkbox',
    component: () => import('./views/pages/DemoCheckbox/index.vue'),
  },
  {
    path: 'dropdown-and-selectors',
    name: 'demo-dropdown',
    displayName: 'Dropdown & Selectors',
    component: () => import('./views/pages/DemoDropdowns/index.vue'),
  },
  {
    path: 'grid',
    name: 'demo-grid',
    displayName: 'Grid',
    component: () => import('./views/pages/DemoGrids/index.vue'),
  },
  {
    path: 'input',
    name: 'demo-input',
    displayName: 'Input',
    component: () => import('./views/pages/DemoInput/index.vue'),
  },
  {
    path: 'item-list',
    name: 'demo-item-list',
    displayName: 'Item List',
    component: () => import('./views/pages/DemoItemlists/index.vue'),
  },
  {
    path: 'modal',
    name: 'demo-modal',
    displayName: 'Modal',
    component: () => import('./views/pages/DemoModals/index.vue'),
  },
  {
    path: 'pagination',
    name: 'demo-pagination',
    displayName: 'Pagination',
    component: () => import('./views/pages/DemoPagination/index.vue'),
  },
  {
    path: 'rating',
    name: 'demo-rating',
    displayName: 'Rating',
    component: () => import('./views/pages/DemoRatings/index.vue'),
  },
  {
    path: 'sidebar',
    name: 'demo-sidebar',
    displayName: 'Sidebar',
    component: () => import('./views/pages/DemoSidebar/index.vue'),
  },
  {
    path: 'snackbar',
    name: 'demo-snackbar',
    displayName: 'Snackbar',
    component: () => import('./views/pages/DemoSnackbar/index.vue'),
  },
  {
    path: 'statistics',
    name: 'demo-statistics',
    displayName: 'Statistics',
    component: () => import('./views/pages/DemoStatistics/index.vue'),
  },
  {
    path: 'tab',
    name: 'demo-tab',
    displayName: 'Tab',
    component: () => import('./views/pages/DemoTab/index.vue'),
  },
  {
    path: 'table',
    name: 'demo-table',
    displayName: 'Table',
    component: () => import('./views/pages/DemoTable/index.vue'),
  },
  {
    path: 'toast',
    name: 'demo-toast',
    displayName: 'Toast',
    component: () => import('./views/pages/DemoToast/index.vue'),
  },
  {
    path: 'tooltip',
    name: 'demo-tooltip',
    displayName: 'Tooltip',
    component: () => import('./views/pages/DemoTooltip/index.vue'),
  },
];
